language: rust

sudo: false

os:
  - linux

env:
  - RUST_BACKTRACE=1

matrix:
  include:
    - rust: 1.20.0
      script:
        - cargo test -vv --no-default-features
        - cargo test -vv --features 'test-readme build-binary'

    - rust: stable
      script:
        - cargo test -vv --no-default-features
        - cargo test -vv --features 'test-readme build-binary'

    - rust: beta
      script:
        - cargo test -vv --no-default-features
        - cargo test -vv --features 'test-readme build-binary'

    - rust: nightly
      script:
        - cargo test -vv --no-default-features
        - cargo test -vv --no-default-features --features alloc
        - cargo test -vv --features 'nightly test-readme build-binary'

  allow_failures:
    - rust: nightly

cache:
  directories:
    - $TRAVIS_BUILD_DIR/target
    - $HOME/.cargo

