language: rust

sudo: false

os:
  - linux

matrix:
  include:
    - rust: 1.20.0
      script:
        - cargo test --verbose --no-default-features
        - cargo test --verbose --features test-readme

    - rust: stable
      script:
        - cargo test --verbose --no-default-features
        - cargo test --verbose --features test-readme

    - rust: beta
      script:
        - cargo test --verbose --no-default-features
        - cargo test --verbose --features test-readme

    - rust: nightly
      script:
        - cargo test --verbose --no-default-features
        - cargo test --verbose --no-default-features --features alloc
        - cargo test --verbose --features 'nightly test-readme'

  allow_failures:
    - rust: nightly

cache:
  directories:
    - $TRAVIS_BUILD_DIR/target
    - $HOME/.cargo

