[package]
authors = ["Zeyla Hellyer <zeylahellyer@gmail.com>"]
description = "A crate for generating Zalgo text with defined parameters."
documentation = "http://docs.rs/zalgo"
homepage = "https://github.com/zeyla/zalgo.rs"
keywords = ["zalgo", "no_std"]
license = "ISC"
name = "zalgo"
readme = "README.md"
repository = "https://github.com/zeyla/zalgo.rs.git"
version = "0.2.0"

[dependencies]
bitflags = "^1.0"
rand = { version = "^0.4", default-features = false }

[build-dependencies]
rustc_version = "^0.2"

[[bin]]
name = "zalgo"
doc = false
required-features = ["std"]

[[example]]
name = "apply"
required-features = ["std"]

[features]
default = ["std"]
nightly = []
std = ["rand/std"]
