[package]
authors = ["Austin Hellyer <hello@austinhellyer.me>"]
description = "A crate for generating Zalgo text with defined parameters."
documentation = "http://docs.austinhellyer.me/zalgo"
homepage = "https://gitlab.com/kalasi/zalgo.rs"
keywords = ["zalgo"]
license = "ISC"
name = "zalgo"
readme = "README.md"
repository = "https://gitlab.com/kalasi/zalgo.rs.git"
version = "0.1.1"

[dependencies]
rand = "^0.3"

[[bin]]
doc = false
name = "zalgo"
path = "bin/zalgo.rs"
