[package]
authors = ["Zeyla Hellyer <zeylahellyer@gmail.com>"]
description = "A crate for generating Zalgo text with defined parameters."
documentation = "http://docs.rs/zalgo"
homepage = "https://github.com/zeyla/zalgo.rs"
keywords = ["zalgo"]
license = "ISC"
name = "zalgo"
readme = "README.md"
repository = "https://github.com/zeyla/zalgo.rs.git"
version = "0.1.1"

[dependencies]
rand = "^0.4"

[[bin]]
doc = false
name = "zalgo"
path = "bin/zalgo.rs"
